# Generated by Django 3.1 on 2020-08-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('image', models.ImageField(upload_to='')),
                ('is_refugee', models.BooleanField()),
                ('rating_val', models.FloatField(blank=True)),
                ('rating_num', models.IntegerField(blank=True)),
            ],
        ),
    ]
