# Generated by Django 3.1 on 2020-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userclass', '0005_auto_20200813_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='is_refugee',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
