version: '3'

services:
  
  django_webserver:
    image: hirearefugee/india
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
    - ${HOME}/workspace:/home/gandhi/workspace
    user: gandhi
  
  redis_broker:
    image: redis:5
    ports: 
    - 6379:6379
#  postgres:
#    image: postgres
#    environment: 
#      - POSTGRES_PASSWORD=postgres

