version: '3'

services:
  
  django_webserver:
    image: hirearefugee/django_webserver
    build:
      context: ../django_webserver
      dockerfile: Dockerfile
    environment: 
    - USE_GUNICORN_NGINX=${USE_GUNICORN_NGINX}
    ports:
    - 8000:8000
    volumes:
    - ${HOME}/workspace:/media/docker/workspace
    user: gandhi
  
  redis_broker:
    image: redis:5
    ports: 
    - 6379:6379

  postgres_server:
    image: hirearefugee/postgres_server
    build:
      context: ../postgres_server
      dockerfile: Dockerfile
    restart: always
    ports:
    - 5430:5432 # postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ${HOME}/workspace:/media/docker/workspace
      - ${HOME}/artifacts/postgres:/var/lib/postgresql/data
  

  nginx_proxy:
    image: hirearefugee/nginx_proxy
    build:
      context: ../nginx_proxy
      dockerfile: Dockerfile
    ports:
    - ${NGINX_PORT}:80 # browser
    volumes:
    - ${HOME}/workspace:/media/docker/workspace
    #volumes:
    #- django_webserver