version: '3'

services:
  
  django_webserver:
    image: hirearefugee/india
    build:
      context: ../india
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
    - ${HOME}/workspace:/home/gandhi/workspace
    user: gandhi
  
  redis_broker:
    image: redis:5
    ports: 
    - 6379:6379

  postgres_server:
    image: hirearefugee/skopje
    build:
      context: ../skopje
      dockerfile: Dockerfile
    restart: always
    ports:
    - 8891:8891 # jupyter (development)
    - 5430:5432 # postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ${HOME}/workspace:/media/docker/workspace
      - ${HOME}/artifacts/postgres:/var/lib/postgresql/data